server {
    listen 80;
    server_name _;
    root /var/www/html/public;
    index index.php;

    client_max_body_size 20M;

    location /uploads/ {
        try_files $uri =404;
    }

    location /assets/ {
        try_files $uri =404;
    }

    location = /api.php {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/api.php;
        fastcgi_param SCRIPT_NAME /api.php;
        fastcgi_pass app:9000;
    }

    location / {
        try_files $uri $uri/ /index.php?route=$uri&$query_string;
    }

    location = /index.php {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        fastcgi_param SCRIPT_NAME /index.php;
        fastcgi_pass app:9000;
    }

    location ~ \.php$ {
        return 404;
    }
}

